--DROP TABLES--



TRUNCATE TABLE ACCEDER;
TRUNCATE TABLE CLIENTE;
TRUNCATE TABLE LOCAL;
TRUNCATE TABLE BEBIDAS;
TRUNCATE TABLE MAQUINA;
TRUNCATE TABLE CONTENER;
TRUNCATE TABLE JUEGO;
TRUNCATE TABLE BARRA;
TRUNCATE TABLE BEBIDAS;
TRUNCATE TABLE CRUPIER;
TRUNCATE TABLE CAMARERO;
TRUNCATE TABLE EMPLEADO;


